add riverpod
meimodev/palakat pull request #2
Opened 2024-10-06 11:19 UTC by Gifriend

so tambah yang riverpod
![Screenshot (1467)](https://github.com/user-attachments/assets/aa5f5164-d13f-42ae-848f-3054fbdd1d4c)

2024-10-07 02:07 UTC, meimodev requested changes

2024-10-07 02:07 UTC, meimodev commented on lib/features/song_detail/presentations/song_detail_screen.dart
> +    WidgetsBinding.instance.addPostFrameCallback((_) {
sebenarnya nda perlu pake postframe callback sih, 
mr kyapa dia error kalo call loadSongParts disini karna dia bagusnya pangge di dalam controller/riverpod build(), coba check dashboard_controller.dart

2024-10-07 02:07 UTC, meimodev commented on lib/features/song_detail/presentations/song_detail_screen.dart
> +    final parts = ref.watch(songDetailControllerProvider);
deng jang lupa nama variabel, bagusnya iko sma deng tu file laeng, yang pake nama controller & state

2024-10-07 03:43 UTC, Gifriend commented on lib/features/song_detail/presentations/song_detail_screen.dart
> +    final parts = ref.watch(songDetailControllerProvider);
ohioren, okey

2024-10-29 07:14 UTC, meimodev approved these changes
LGTM

2024-10-29 07:14 UTC, merged