make validation on input text widget
meimodev/palakat pull request #3
Opened 2024-12-28 13:20 UTC by Gifriend

disini untuk yang doe bagian input text widget so jadi, cmn dpe bagain dropdown sih yang ketika langsung tekan submit, dia nda muncul dpe error text

2024-12-28 22:53 UTC, meimodev requested changes

2024-12-28 22:53 UTC, meimodev commented on lib/core/widgets/input/input_widget.dart
trng nda perlu passing variabel validators itu di dalam InputWidgetVariant, cukup di handle dari InputWidget. yang di passing di InputWidgetVariant cuman yang errorText dari errorMessage for handle perubahan warna yang per InputWidgetVariant mungkin akan beda.

2024-12-28 22:53 UTC, meimodev commented on lib/core/widgets/input/input_variant_dropdown_widget.dart
Kalo ini memang blum ada yang for handle kalo ada errorMessage, beking jo kalo ada errorMessage, rubah d p border color beking warna negative, kalo yang muncul text tentang d p error so handle di InputWidget, jadi so nda perlu disini

2024-12-28 22:53 UTC, meimodev commented on lib/features/publishing/presentations/activity_publish/activity_publish_screen.dart
yang d p proses validasi (function di dalam validator) bagusnya di pindah dalam file controller screen itu, biar sbntr d p validator di satu tampa

2024-12-28 22:53 UTC, meimodev commented on lib/features/publishing/presentations/activity_publish/activity_publish_screen.dart
> +  final formKey = GlobalKey<FormState>();
trng nda pake yang cara ini sih, jadi nda perlu set property key yang di dalam Form

2024-12-28 22:53 UTC, meimodev commented on lib/features/publishing/presentations/activity_publish/activity_publish_screen.dart
jdi yang di screen, property validator itu beking jo function yang return value dari variabel state, contoh validators: controller.validateLocation

di controller
validateLocation(){
// check validation, kalo nda valid tinggal alter state.errorTextLocation
return state.errorTextLocation
}

2025-01-03 12:00 UTC, Gifriend commented
kt so coba beking, cmn dpe error text nda muncul, yang muncul cmn snackbar klo field kosong, dpe error text itu nanti muncul kalo field so isi kong se kosong ulang

2025-01-04 03:23 UTC, Gifriend commented
ini kita so coba beking, dia boleh pas submit muncul error text mar yang jadi ini cmn bagian inputtext, yang dropdown bisa mar dpe errortext musti langsung se maso di activitypublish deng kalo bagian input text dia kalo so se maso input kong hapus, mo muncul yang error text dengan validator

2025-01-08 06:44 UTC, meimodev requested changes

2025-01-08 06:44 UTC, meimodev commented on lib/core/widgets/input/input_variant_dropdown_widget.dart
ini le nda ush handle d p error di widget variant, nanti handle di input_widget.dart

2025-01-08 06:44 UTC, meimodev commented on lib/core/widgets/input/input_widget.dart
> +    this.autoValidateMode = AutovalidateMode.disabled,
ini comment jo, dari nda pake

2025-01-08 06:44 UTC, meimodev commented on lib/core/widgets/input/input_widget.dart
> +    this.autoValidateMode = AutovalidateMode.disabled,
ini le comment

2025-01-08 06:44 UTC, meimodev commented on lib/core/widgets/input/input_widget.dart
> +                errorText: widget.errorText,
errorText ini nda ush passing

2025-01-08 06:44 UTC, meimodev commented on lib/core/widgets/input/input_widget.dart
> +                errorText: widget.errorText,
comment jo

2025-01-08 06:44 UTC, meimodev commented on lib/core/widgets/input/input_widget.dart
> +                errorText: widget.errorText,
ini le nd ush passing, comment aja

2025-01-08 06:44 UTC, meimodev commented on lib/features/publishing/presentations/activity_publish/activity_publish_screen.dart
> +            child: Form(
nda ush pake widget Form, soalnya trng nda pake d p fitur autoValidateMode

2025-01-08 06:44 UTC, meimodev commented on lib/features/publishing/presentations/activity_publish/activity_publish_screen.dart
> +        onTap: () {
ini taruh di controller, di function submit

2025-01-08 06:44 UTC, meimodev commented on lib/features/publishing/presentations/activity_publish/activity_publish_state.dart
>  class ActivityPublishState {
ini boleh pake freezed, biar nd perlu tulis dia p copywith function deng constructor

2025-01-08 06:44 UTC, meimodev commented on lib/features/publishing/presentations/activity_publish/activity_publish_state.dart
>  class ActivityPublishState {
boleh check di class state yang lain

2025-05-31 02:36 UTC, meimodev approved these changes

2025-05-31 02:36 UTC, merged